apiVersion: v1
kind: ConfigMap
metadata:
  name: communicator-master-config
data:
  REDIS_HOST: redis-master
  REDIS_PORT: "6379"
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: communicator-writer
  labels:
    app: communicator-writer
spec:
  selector:
    matchLabels:
      name: communicator-writer
  template:
    metadata:
      labels:
        name: communicator-writer
    spec:
      containers:
        - name: communicator-writer
          image: alexeytsarev/redis_communicator
          env:
            - name: APP_ROLE
              value: writer
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: communicator-master-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: communicator-master-config
                  key: REDIS_PORT
