apiVersion: v1
kind: ConfigMap
metadata:
  name: communicator-slave-config
data:
  REDIS_HOST: redis-slave
  REDIS_PORT: "6379"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: communicator-reader
  labels:
    app: communicator-reader
spec:
  selector:
    matchLabels:
      name: communicator-reader
  replicas: 1
  template:
    metadata:
      labels:
        name: communicator-reader
    spec:
      containers:
        - name: communicator-reader
          image: alexeytsarev/redis_communicator
          env:
            - name: APP_ROLE
              value: reader
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: communicator-slave-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: communicator-slave-config
                  key: REDIS_PORT
